sylius_resource:
    resources:
        app.product_color:
            classes:
                model: App\Entity\ProductColor
                
sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                show_color:
                    priority: 18
                    template: 'Shop/showProductColor.html.twig'
